app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use App\Group;

Route::get('check', function(){
    $group = Group::find(2);

    dd($group->users->random(1));
});

Route::get('/', 'PagesController@home');
Route::get('search', 'SearchController@search');
Route::get('about', 'PagesController@about');
Route::get('terms', 'PagesController@terms');
Route::get('contact', 'PagesController@contact');
Route::get('privacy', 'PagesController@privacy');

Route::post('register', 'AuthController@register');
Route::post('login', 'AuthController@login');
Route::get('logout', 'AuthController@logout');

Route::get('facebook_redirect', 'AuthController@facebookRedirect');
Route::get('facebook_login', 'AuthController@facebookLogin');
Route::get('verify_account', ['as' => 'auth.verify', 'uses' => 'AuthController@verify']);

Route::resource('user', 'UsersController');
Route::get('user/{id}/groups', ['as' => 'user.show_groups', 'uses' => 'UsersController@show_groups']);

Route::resource('group', 'GroupsController');
Route::post('groups/{group}/add_moderator', ['as' => 'group.add_moderator', 'uses' => 'GroupsController@addModerator']);
Route::delete('groups/{group}/remove_moderator', ['as' => 'group.remove_moderator', 'uses' => 'GroupsController@removeModerator']);
Route::get('groups/{group}/accept_member/{user}', ['as' => 'group.accept_member', 'uses' => 'GroupsController@acceptMember']);
Route::get('groups/{group}/reject_member/{user}', ['as' => 'group.reject_member', 'uses' => 'GroupsController@rejectMember']);
Route::get('group/{group}/join', ['as' => 'group.join', 'uses' => 'GroupsController@join']);
Route::get('group/{group}/leave', ['as' => 'group.leave', 'uses' => 'GroupsController@leave']);

Route::group(['prefix' => 'group/{group}'], function () {
    Route::resource('event', 'EventsController');
    Route::resource('post', 'PostsController');
});

Route::post('post/{post}/add_comment', ['as' => 'post.comment', 'uses' => 'CommentsController@store']);

Route::resource('message', 'MessagesController');

Route::post('request', 'AuthController@requestPasswordReset');
Route::get('reset_password', ['as' => 'password.reset', 'uses' => 'AuthController@performPasswordReset']);
Route::post('complete', 'AuthController@completePasswordReset');

Route::get('category/{category}/sub_categories', 'CategoriesController@getSubCategories');
Route::get('country/{country}/cities', 'CountriesController@getCities');

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'image', 'description', 'locality', 'category_id', 'city_id', 'country_id', 'sub_category_id', 'privacy'];

    /*
    |--------------------------------------------------------------------------
    | Getters
    |--------------------------------------------------------------------------
    |
    */

    public function getThumbnailUrlAttribute(){
        if( !empty($this->image) )
            return url('uploads/tn-' . $this->image);

        return url('images/group_placeholder.jpg');
    }

    public function getAdminAttribute(){
        return $this->admins()->first();
    }

    public function getMemberCountAttribute(){
        return count($this->members);
    }

    /*
    |--------------------------------------------------------------------------
    | Relations
    |--------------------------------------------------------------------------
    |
    */

    public function all_users(){
        return $this->belongsToMany('App\User')->withPivot('user_id', 'group_id', 'group_role_id');
    }

    public function users(){
        return $this->belongsToMany('App\User')->withPivot('user_id', 'group_id', 'group_role_id')->wherePivot('status', APPROVED_MEMBER);
    }

    public function pending_users(){
        return $this->belongsToMany('App\User')->withPivot('user_id', 'group_id', 'group_role_id')->wherePivot('status', PENDING_MEMBER);
    }

    /**
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function members(){
        return $this->belongsToMany('App\User')->withPivot('user_id', 'group_id', 'group_role_id')->wherePivot('group_role_id', 0)->wherePivot('status', APPROVED_MEMBER);
    }

    public function admins(){
        return $this->belongsToMany('App\User')->withPivot('user_id', 'group_id', 'group_role_id')->wherePivot('group_role_id', GROUP_ADMIN)->wherePivot('status', APPROVED_MEMBER);
    }

    public function moderators(){
        return $this->belongsToMany('App\User')->withPivot('user_id', 'group_id', 'group_role_id')->wherePivot('group_role_id', GROUP_MODERATOR)->wherePivot('status', APPROVED_MEMBER);
    }

    public function events(){
        return $this->hasMany('App\Event');
    }

    public function posts(){
        return $this->hasMany('App\Post');
    }

    public function category(){
        return $this->belongsTo('App\Category');
    }

    /*
    |--------------------------------------------------------------------------
    | Relations
    |--------------------------------------------------------------------------
    |
    */

    public function appointNewAdmin(){
        if( !$this->moderators->isEmpty() ){
            $moderator = $this->moderators->random(1);

            $this->users()->detach($moderator);
            $this->users()->attach($moderator, ['group_role_id' => GROUP_ADMIN]);
        }
        else if( !$this->members->isEmpty() ){
            $member = $this->members->random(1);

            $this->users()->detach($member);
            $this->users()->attach($member, ['group_role_id' => GROUP_ADMIN]);
        }
        else{
            $this->delete();
        }
    }
}

app/Http/Controllers/GroupsController.php
<?php

namespace App\Http\Controllers;

use App\Group;
use App\User;
use Sentinel;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class GroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $data['user'] = Sentinel::getUser();

        return view('group.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $this->validate($request, ['name' => 'required', 'privacy' => 'required']);

        $user = Sentinel::getUser();

        $group = new Group($request->except('image'));

        $group->image = ($request->hasFile('image')) ? $this->upload($request->file('image')) : null;

        $group->save();

        $group->users()->attach($user, ['group_role_id' => GROUP_ADMIN, 'status' => APPROVED_MEMBER]);

        return redirect()->route('group.show', ['id' => $group->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $data['group'] = Group::findOrFail($id);

        if(Sentinel::guest()){
            return view('group.show_guest', $data);
        }
        else{
            return view('group.show', $data);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $data['group'] = Group::findOrFail($id);

        return view('group.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, ['name' => 'required', 'privacy' => 'required']);

        $group = Group::find($id);

        $group->fill($request->except('image'));

        $group->image = ($request->hasFile('image')) ? $this->upload($request->file('image')) : $group->image;

        $group->save();

        return redirect()->route('group.show', ['id' => $group->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $group = Group::find($id);

        $group->delete();

        return redirect()->to('/');
    }

    public function join($id){
        $user = Sentinel::getUser();

        $group = Group::find($id);

        $status = ( $group->privacy == PRIVATE_GROUP ) ? PENDING_MEMBER : APPROVED_MEMBER;

        $group->users()->attach($user, ['status' => $status]);

        return redirect()->route('group.show', ['group' => $group->id]);
    }

    public function leave($id){
        $user = Sentinel::getUser();

        $group = Group::find($id);

        if( $group->admin->id == $user->id ){
            $group->appointNewAdmin();
        }

        $group->users()->detach($user);

        return redirect()->route('group.show', ['group' => $group->id]);
    }

    public function addModerator(Request $request, $group){
        $moderator = User::find($request->input('user'));

        $group = Group::find($group);

        $group->users()->detach($moderator);
        $group->users()->attach($moderator, ['group_role_id' => GROUP_MODERATOR]);

        return redirect()->back();
    }

    public function removeModerator(Request $request, $group){
        $moderator = User::find($request->input('user'));

        $group = Group::find($group);

        $group->users()->detach($moderator);
        $group->users()->attach($moderator, ['group_role_id' => 0]);

        return redirect()->back();
    }

    public function acceptMember($group, $user){
        $user = User::find($user);

        $group = Group::find($group);

        $group->all_users()->detach($user);
        $group->all_users()->attach($user, ['group_role_id' => 0, 'status' => APPROVED_MEMBER]);

        return redirect()->back();
    }

    public function rejectMember($group, $user){
        $user = User::find($user);

        $group = Group::find($group);

        $group->all_users()->detach($user);

        return redirect()->back();
    }
}

resources/views/group/_form.blade.php
<div class="profile_update_right_area2_full_w">
    <div class="profile_update_right_heding"><h1>Group Name</h1></div>
    <div class="profile_update_right_field">
        {!! Form::text('name', null, ['class' => 'profile_update_right_input_style1']) !!}
    </div>
</div>

<div class="profile_update_right_area2_full_w">
    <div class="profile_update_right_heding"><h1>Description</h1></div>
    <div class="profile_update_right_field">
        {!! Form::textarea('description', null, ['class' => 'profile_update_right_textarea_style1']) !!}
    </div>
</div>


<div class="profile_update_right_area2_full_w">
    <div class="profile_update_right_heding"><h1>Category</h1></div>
    <div class="profile_update_right_field">
        {!! Form::select('category_id', $categories, null, ['class' => 'profile_update_right_select_style1']) !!}
    </div>
</div>

<div class="profile_update_right_area2_full_w">
    <div class="profile_update_right_heding"><h1>SUB Category</h1></div>
    <div class="profile_update_right_field">
        {!! Form::select('sub_category_id', $sub_categories, null, ['class' => 'profile_update_right_select_style1']) !!}
    </div>
</div>

<div class="profile_update_right_area2_full_w">
    <div class="profile_update_right_heding"><h1>COUNTRY</h1></div>
    <div class="profile_update_right_field">
        {!! Form::select('country_id', $countries, null, ['class' => 'profile_update_right_select_style1']) !!}
    </div>
</div>

<div class="profile_update_right_area2_full_w">
    <div class="profile_update_right_heding"><h1>City</h1></div>
    <div class="profile_update_right_field">
        {!! Form::select('city_id', $cities, null, ['class' => 'profile_update_right_select_style1']) !!}</div>
</div>

<div class="profile_update_right_area2_full_w">
    <div class="profile_update_right_heding"><h1>Locality</h1></div>
    <div class="profile_update_right_field">{!! Form::text('locality', null, ['class' => 'profile_update_right_input_style1']) !!}</div>
</div>

<div class="profile_update_right_area2_full_w">
    <div class="profile_update_right_heding"><h1>Privacy</h1></div>
    <div class="profile_update_right_field">{!! Form::radio('privacy', PRIVATE_GROUP, null, null) !!} Private</div>
    <div class="profile_update_right_field">{!! Form::radio('privacy', PUBLIC_GROUP, true, null) !!} Public</div>
</div>

<div class="profile_update_right_area2_full_w">
    <div class="profile_update_right_heding"><h1>Upload Image</h1></div>
    <div class="profile_update_right_field"><div class="profile_update_right_browse_area">{!! Form::file('image', ['class' => 'profile_update_browse_style', 'accept' => 'image/*']) !!}</div></div>
</div>


<input type="submit" value="SAVE" class="save_but1" />

resources/views/group/_info.blade.php
<div class="profile_update_left_area2">

    <div class="grouppage_squre_image_cont"><img src="{{ $group->thumbnail_url }}" alt="" class="grouppage_squre_image"/></div>

    <h1 class="status_heading">Group Name</h1>
    <div class="grouppage_title">{{ $group->name }}</div>
    <h1 class="status_heading">Founded on</h1>
    <div class="grouppage_title">{{ \Carbon\Carbon::parse($group->created_at)->toFormattedDateString() }}</div>

    <h1 class="status_heading">Admin</h1><br>
    <div class="profile_img_area2"><a href="{{ route('user.show', ['id' => $group->admin->id]) }}"><img src="{{ $group->admin->thumbnail_url }}" alt="" /></a></div>
    <div class="grouppage_title"><a href="{{ route('user.show', ['id' => $group->admin->id]) }}">{{ $group->admin->name }}</a></div>

    @if( !$group->moderators->isEmpty() )
        <h1 class="status_heading">Moderators</h1><br>

        @foreach( $group->moderators as $moderator )
            <div class="profile_img_area2"><a href="{{ route('user.show', ['id' => $moderator->id]) }}"><img src="{{ $moderator->thumbnail_url }}" alt="" /></a></div>
            <div class="grouppage_title"><a href="{{ route('user.show', ['id' => $moderator->id]) }}">{{ $moderator->name }}</a></div>
        @endforeach
    @endif

    @if ( $auth )
        @if ( $group->all_users->contains('id', $auth->id) )
            @if( $group->users->contains('id', $auth->id) )
                @if($group->admin->id != $auth->id)
                    <a href="{{ route('group.leave', ['group' => $group->id]) }}" class="edit_profile_but">Leave Group</a>
                @endif
            @else
                <a href="{{ route('group.leave', ['group' => $group->id]) }}" class="edit_profile_but">Cancel Request</a>
            @endif
        @else
            <a href="{{ route('group.join', ['group' => $group->id]) }}" class="groups_join_but">Join Group</a>
        @endif
    @endif
</div>

resources/views/group/create.blade.php
@extends('master')

@section('jumbotron')
    @include('partials._jumbotron-sm')
@endsection

@section('content')
    <div class="body_contanear">
        <div class="contanear">
            @include('profile._info')

            <div class="profile_update_right_area2">
                {!! Form::open(['action' => 'GroupsController@store', 'files' => true]) !!}
                    @include('group._form')
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/group/edit.blade.php
@extends('master')

@section('jumbotron')
    @include('partials._jumbotron-sm')
@endsection

@section('content')
    <div class="body_contanear">
        <div class="contanear">

            @include('group._info')

            <div class="profile_update_right_area2">
                {!! Form::model($group, ['method' => 'PATCH', 'action' => ['GroupsController@update', $group->id], 'files' => true]) !!}
                    @include('group._form')
                {!! Form::close() !!}


                    <div class="group_admin_heading2"><h1>Add / Remove Moderator</h1></div>

                {!! Form::open(['route' => ['group.remove_moderator', $group->id], 'method' => 'DELETE']) !!}
                    <div class="add_remove_moderator_box1">
                        <div class="add_remove_moderator_picture"><img src="{{ url('images/demo_profile.jpg') }}" alt="" /></div>
                        <div class="add_remove_moderator_text_area">
                            {!! Form::select('user', $group->moderators->lists('name', 'id'), null, ['class' => 'add_remove_moderator_input_style1']) !!}
                            <input type="submit" value="DELETE" class="add_remove_moderator_submit_but" />
                        </div>
                    </div>
                {!! Form::close() !!}

                {!! Form::open(['route' => ['group.add_moderator', $group->id]]) !!}
                    <div class="add_remove_moderator_box1">
                        <div class="add_remove_moderator_picture"><img src="{{ url('images/demo_profile.jpg') }}" alt="" /></div>
                        <div class="add_remove_moderator_text_area">
                            {!! Form::select('user', $group->members->lists('name', 'id'), null, ['class' => 'add_remove_moderator_input_style1']) !!}
                            <input type="submit" value="ADD" class="add_remove_moderator_submit_but" />
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/group/show_guest.blade.php
@extends('master')

@section('jumbotron')
    @include('partials._jumbotron')
@endsection

@section('content')
    <div class="body_contanear">
        <div class="contanear">
            <div class="founded_page_left_area">
                <div class="active_group_img_area2"><img src="{{ $group->thumbnail_url }}" alt="" /></div>
                <h1>Group Name</h1>
                <p>{{ $group->name }}</p>
                <h1>Founded on</h1>
                <p>{{ \Carbon\Carbon::parse($group->created_at)->toFormattedDateString() }}</p>
                <h1>Managed By</h1>
                <div class="profile_img_area"><img src="{{ $group->admin->thumbnail_url }}" alt="" /></div>
                <p>{{ $group->admin->name }}</p>
                <h1>Available</h1>
            </div>

            <div class="founded_page_right_area">
                <h1>{{ $group->name }}</h1>
                <h2>Description</h2>
                <p>{{ $group->description }}</p>
                <a href="#login-box2" class="signup_but2 login-window2"><img src="{{ url('images/login_but.png') }}" alt="" /> Already Member? Login</a>
                <a href="#login-box" class="login_but2 login-window"><img src="{{ url('images/sign_up_but.png') }}" alt="" /> New Member? Signup</a>

            </div>
        </div>
    </div>
@endsection